package com.pillskeeper.enums

enum class ErrorTypeEnum {
    FIREBASE_DB_READING,
    FIREBASE_STORAGE_READING,
    FIREBASE_STORAGE_GENERIC_ERROR,
    FIREBASE_OBJECT_ALREADY_EXISTS,
    WRITING_COMPLETE
}